### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by clauber115**
Recommend adding rake to the apt-get install command, as it's required for the plugin to work

### CODE REVIEW

**Comment by clauber115** [comment]
From Luke: I think that should be part of the plugin install and I also think it needs to be via docker so no one has to have Ruby and deal with all that fun

**Comment by clauber115** [comment]
I tend to agree with Luke's assessment that we make it the Docker container.

**Comment by lkorth** [comment]
@clauber115 see what you think about these directions instead

**Review by lkorth — APPROVED** [review]

**Comment by lkorth** [comment]
If you're happy with the changes, I've approved the PR, feel free to go ahead and merge

**Review by clauber115 — COMMENTED** [review]
Awesome, thanks for the clarity and changes!

**Pull request merged**
